### ISSUE TITLE
min vs umin for size

### ISSUE THREAD

**Issue by ruv** [larsbrinkhoff/lbForth#22]
Why do you use `min` but not `umin` in the code like [the following](https://github.com/larsbrinkhoff/lbForth/blob/fb785f783931eb194abcb989ec83ba75b914129f/targets/x86/target.fth#L9):

`: name, ( a u -- ) #name min dup c, tuck move, offset, ;
`

Here `min` protects against too long `u`, but not from negative `u` (or very long positive ;).

**Comment by larsbrinkhoff** [comment]
Sorry, just sloppiness.  It really should be `umin`.  But I suppose it doesn't matter much, because strings rarely are that long.

**Comment by ruv** [comment]
Yes, strings themselves are usually not so long. Negative length can be result of a bug in calculations with address arithmetic.
