### ISSUE TITLE
Clean up asm.js target.fth

### ISSUE THREAD

**Issue by larsbrinkhoff** [larsbrinkhoff/lbForth#35]
The asm.js target.fth has two definitions for `header,`, which is probably a mistake.

Also, `docol,` etc compile a zero cell before the code field proper.  I'm not sure that's by design or not.  Is that the place for the "codeid", or the does field?  I think the latter.  But then the zero could probably move to `header,` like in the C target.

@pipcet, do you have any comment on this?

**Comment by pipcet** [comment]
Both mistakes. I missed that there was a double definition of `header,` and added the `0 ,` to get things working, but I should have just deleted the second definition of `header,`, I think.

**Comment by larsbrinkhoff** [comment]
> Both mistakes.

Maybe not!  Because asm.fth says

    : header   parse-name header, 'dodoes , scount @ , reveal ;

**Comment by larsbrinkhoff** [comment]
Fixed by df617ad and b6e66b2.

**Comment by larsbrinkhoff** [comment]
Fixed by 9cda437.
