### ISSUE TITLE
make fail on cygwin-x86_64

### ISSUE THREAD

**Issue by structure-charger** [larsbrinkhoff/lbForth#78]
after ./configure , excute make ,the resault is Segmentation fault . stack dump is below:
Exception: STATUS_ACCESS_VIOLATION at rip=00180194D3D
rax=0000000044000000 rbx=0000000000000073 rcx=0000000044000000
rdx=0000000000000001 rsi=000000060005F318 rdi=0000000044000000
r8 =00000000FFFFAE10 r9 =0000000000000006 r10=0000000000000000
r11=0000000000000000 r12=0000000000000000 r13=00000000FFFFAA48
r14=00000000FFFFD680 r15=00000000FFFFAB40
rbp=00000000FFFFAB30 rsp=00000000FFFFA8D8
program=D:\Cwin\bin\make.exe, pid 5760, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame             Function              Args
000FFFFAB30  00180194D3D  (00000000014, 000FFFFAA38, 0060005E288, 000FFFFAA48)
000FFFFAB30  001801A0916  (000FFFFACB0, 0060005F308, 000FFFFAE10, 0060006040C)
0060005F328  001801BD8AF  (000FFFFAED0, 00600051AD3, 00000000001, 00000000000)
0060005F328  001801197EB  (000FFFFAED0, 00600051AD3, 00000000001, 00000000000)
0060005F328  0010041368A  (0010042B6EF, 00100435E40, 00044000000, 0060005B1D0)
00000000000  00100416D8A  (00000000001, 00000000001, 0018013F700, 00000000003)
000FFFFB008  00100417EEE  (00000000010, 00000000000, 000FFFFB278, 00600000002)
00100435CF0  00100417CD9  (00000000001, 00000000001, 0018013F700, 00100000003)
000FFFFB278  00100417EEE  (0010041C161, 0060005192E, 00100435E00, 2A2D736500000000)
0060005B250  00100418234  (00300000000, 00000000000, 00000000000, 00000000000)
000FFFFB3D0  00100423B93  (000FFFFCC50, 00600000160, 00180047B51, 00180046B90)
000FFFFCCB0  00180047BC2  (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00180045863  (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFFFF0  00180045914  (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace

**Comment by Phi-Ho** [comment]
Hi,

I installed Cygwin with "setup-x86.exe" :

$ uname -m
i686

lbForth was successfully built. 

Hope this helps.

Regards,

phiho

**Comment by larsbrinkhoff** [comment]
Sorry @structure-charger, it seems I completely missed your post.

The reason for the failure might be because you are using the 64-bit version of Cygwin.  lbForth does not support x86-64.
