### ISSUE TITLE
load-address

### ISSUE THREAD

**Issue by Phi-Ho** [larsbrinkhoff/lbForth#85]
It seems that "load-address" is missing for meta compiling?

**Comment by larsbrinkhoff** [comment]
`load-address` should be defined in a target-specific file.  For example targets/x86/linux/params.fth has it set to 08048000.

**Comment by Phi-Ho** [comment]
Hello,

Thank you so much for your reply.

Please excuse my ignorance, would you please point me in the right
direction as to how to find out these constants (they are defined as
constants?) for Windows and RISC V

It is quite emotional when seeing your forth for PDP-1. I am strongly
attached to PDP 8, 11, 16 and 10.

Best regards,

phiho

**Comment by Phi-Ho** [comment]
PS: Sorry, I found where these constants are defined.

**Comment by larsbrinkhoff** [comment]
I'm glad you found what you were looking for.

Some of the target directories are only half-baked ideas.  For example, there is no working code for the PDP-1 or 10.  There is a PDP-8 cross compiler in my xForth repository.
