### ISSUE TITLE
include target.fth

### ISSUE THREAD

**Issue by Phi-Ho** [larsbrinkhoff/lbForth#90]
Hi,

'target.fth' is included in two different places:

src\compile.fth(36): include target.fth
src\kernel.fth(109): include target.fth

and 'target.fth' exists in 3 relevant places:

.      (build root)
./target/x86 
./target/x86/windows

Please advise which of these three would be included in 'src\compile.fth' and 'src\kernel.fth'

I also have two other related questions:

1/- What is the difference between "include" and "require"?
2/- How does "searched" work?

Regards,
phiho

**Comment by larsbrinkhoff** [comment]
`target.fth` is a target-specific file.  Different versions exists for all supported targets.  The file that is included is in the build root, and it's a concatenation of targets/x86/target.fth and targets/x86/windows/targets.fth when you buid for TARGET=x86 OS=windows.

`include` always reads a file, but `require` doesn't if the file has been read previously.

`searched` takes a string and adds it to the file search path list.  `include` etc tries all search paths in the list to find a file.
