### ISSUE TITLE
RISC-V build: Undefined eax

### ISSUE THREAD

**Issue by Phi-Ho** [larsbrinkhoff/lbForth#91]
Dear List,

I am trying to build a RISC-V image and got this error:

PS F:\fun\lbForth\build\wsl\META\w4\FULL> ./i
lbForth
ok
include targets/riscv/build.fth
Undefined: eax

Am I doing something wrong here?

Regards,

phiho

**Comment by larsbrinkhoff** [comment]
You should build the RISC-V target like this: `make TARGET=riscv OS=linux`
