### ISSUE TITLE
Undefined: '

### ISSUE THREAD

**Issue by Phi-Ho** [larsbrinkhoff/lbForth#92]
Hello,

Please advise what I am doing wrong here to make tick ( ' ) undefined:
Please find related info appended below.

Regards,

phiho

$ ./i.exe
lbForth
ok
include search.fth
 ok
' only
 ok
' forth
 ok
' definitions
 ok
' also
 ok
' t-words
Undefined: t-words
' also
Undefined: '

**Comment by larsbrinkhoff** [comment]
This a known bug: #20.  The search order is messed up when there is an exception.  To get back to a sane state, type `only forth`.

**Comment by Phi-Ho** [comment]
Hi,

Thanks for the info but actually "only forth" does not get back to the same
state. The system seems to be deeply corrupted.

' t-words
Undefined: t-words
 ok
' forth
 ok
' also
 ok
include search.fth
 ok
' t-words
Undefined: t-words
' meta
Undefined: '
words
Undefined: words
only forth
 ok
words
vocs vocabulary body>xt order set-order ?voc-limit only order! n! forth
only wordlist (wordlist) definitions set-current
.....
get-std-handle  ok
' meta
Undefined: meta
' t-words
Undefined: '
only forth
 ok
include search.fth
Undefined: definitions
only forth
Order: only only
Current: only

Stack underflow
$
