### ISSUE TITLE
QEMU for RISC-V lbForth

### ISSUE THREAD

**Issue by Phi-Ho** [larsbrinkhoff/lbForth#95]
Hello,

Now that I got qemu-system-riscv32.exe and qemu-system-riscv64.exe, which emulator (elf file and command line to invoke qemu) is needed to properly run RISC-V lbForth

Thanks for sharing.

Regards,

phiho

**Comment by larsbrinkhoff** [comment]
I *believe* you should use qemu-user-riscv32, but since I don't have this set up properly now I'm not sure.

**Comment by Phi-Ho** [comment]
Hi,

Do you still have a runnable RISC-V lbForth on your computers to verify
reported issues ?

Regards,

phiho

**Comment by larsbrinkhoff** [comment]
Yes.  I built it now and ran the tests successfully.  Attaching a zip file.
[riscv.zip](https://github.com/larsbrinkhoff/lbForth/files/5592401/riscv.zip)

**Comment by Phi-Ho** [comment]
Hi,

Thank you very much.

Would you please share the environment where you just built the attached
RISC-V lbForth so that I can build it on my machine.

Regards,

phiho

**Comment by larsbrinkhoff** [comment]
I built it like this, in two steps:

```
make clean all TARGET=x86 OS=linux
make TARGET=riscv OS=linux
```

If your host is Windows, use `OS=windows` on the first line instead.

**Comment by larsbrinkhoff** [comment]
QEMU isn't needed for *building* a target Forth.  It's just needed for running of testing the target.

**Comment by Phi-Ho** [comment]
Hi,

Thank you for your response, I could build it on my machine but still
cannot run ịt

I would like to run the tests on my machine. How did you do it on your
machine, what tests did you do?

Regards,

**Comment by larsbrinkhoff** [comment]
The test are run with "make check TARET=riscv OS=linux".  The RISC-V binary is run using the script targets/riscv/run.sh.  As you can see, you will need something like `riscv32-linux-user/qemu-riscv32`.  Since it was many years ago I worked on this, I can't say how to do this today.

**Comment by Phi-Ho** [comment]
Hi,

Thank you so much for your clarification. It is great that your RISC-V
environment is still running

I am still struggling.

Regards,

phiho
